version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: weather-backend

    ports:
      - "3000:3000"

    env_file:
      - ./Backend/.env

    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: weather-frontend

    ports:
      - "8080:80"

    depends_on:
      - backend

    restart: unless-stopped