apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: weather-app
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/SROR7/weather-app.git
    targetRevision: main
    path: K8S

  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true